/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controll;

import DataBox.TeamData;
import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Shayan
 */
public class BasketTeamName extends javax.swing.JPanel {

    ControllInterFace controllInterFace;
    ControllCommandSet controllCommandSet;
    jPannel_name_no pannel_name_noA[], pannel_name_noB[];
    ImagePanel imagePanelA, imagePanelB;
    TeamData teamData;
//    String teamdatafilename="seting\\teamData.json";

    /**
     * Creates new form basketTeamName
     *
     * @param controllInterFace
     */
    public BasketTeamName(ControllInterFace controllInterFace) {
        initComponents();
        this.controllInterFace = controllInterFace;
        controllCommandSet = controllInterFace.getControllCommandSet();
        initData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneA = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIntroLine_1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIntroLine_2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIntroLine_3 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIntroLine_4 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIntroLine_5 = new javax.swing.JTextField();
        jPanellShowIntr = new javax.swing.JPanel();
        jToggleButtonShowIntr = new javax.swing.JToggleButton();
        jPanel9 = new javax.swing.JPanel();
        jPanelteamMansB = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanelPicB = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jTextFieldteamname_2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldteamCity_2 = new javax.swing.JTextField();
        jTextFieldteamcoachB = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanelShowTeamB = new javax.swing.JPanel();
        jToggleButtonShowTeamB = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jPanelteamMansA = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanelPicA = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jTextFieldteamname_1 = new javax.swing.JTextField();
        jTextFieldteamCity_1 = new javax.swing.JTextField();
        jTextFieldteamcoachA = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanelShowTeamA = new javax.swing.JPanel();
        jToggleButtonShowTeamA = new javax.swing.JToggleButton();
        jPanel19 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jTextFieldrefree1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldrefree2 = new javax.swing.JTextField();
        jTextFieldrefree3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanelShowrefree = new javax.swing.JPanel();
        jToggleButtonShowrefree = new javax.swing.JToggleButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("خط 1");

        jTextFieldIntroLine_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIntroLine_1.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTextFieldIntroLine_1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIntroLine_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("خط2");

        jTextFieldIntroLine_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIntroLine_2.setText(" ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jTextFieldIntroLine_2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIntroLine_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("خط 3");

        jTextFieldIntroLine_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIntroLine_3.setText(" ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jTextFieldIntroLine_3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIntroLine_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("خط 4");

        jTextFieldIntroLine_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIntroLine_4.setText(" ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jTextFieldIntroLine_4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIntroLine_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("خط 5");

        jTextFieldIntroLine_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIntroLine_5.setText(" ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jTextFieldIntroLine_5, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIntroLine_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel8);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 400, 150));

        jPanellShowIntr.setBackground(new java.awt.Color(153, 153, 153));

        jToggleButtonShowIntr.setText("نمایش معرفی");
        jToggleButtonShowIntr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonShowIntrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanellShowIntrLayout = new javax.swing.GroupLayout(jPanellShowIntr);
        jPanellShowIntr.setLayout(jPanellShowIntrLayout);
        jPanellShowIntrLayout.setHorizontalGroup(
            jPanellShowIntrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellShowIntrLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jToggleButtonShowIntr)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanellShowIntrLayout.setVerticalGroup(
            jPanellShowIntrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellShowIntrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonShowIntr)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.add(jPanellShowIntr, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 400, 70));

        jTabbedPaneA.addTab("معرفی بازی و روزشگاه ", jPanel1);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jPanelteamMansB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelteamMansB.setLayout(new java.awt.GridLayout(0, 1));
        jPanel9.add(jPanelteamMansB);

        jPanel14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        jPanelPicB.setBackground(new java.awt.Color(0, 0, 0));
        jPanelPicB.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanelPicB.setLayout(new java.awt.GridLayout(1, 0));
        jPanel15.add(jPanelPicB);

        jButton3.setText("ورود لوگو");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton3);

        jTextFieldteamname_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldteamname_2.setText("نام");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("نام تیم");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("شهر تیم");

        jTextFieldteamCity_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldteamCity_2.setText("شهر");

        jTextFieldteamcoachB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldteamcoachB.setText("شهر");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("مربی تیم");

        jButton4.setText("خواندن فایل اسامی");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jButton4)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldteamCity_2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldteamname_2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jTextFieldteamcoachB, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldteamname_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldteamCity_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldteamcoachB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelShowTeamB.setBackground(new java.awt.Color(153, 153, 153));

        jToggleButtonShowTeamB.setText("نمایش اسامی");
        jToggleButtonShowTeamB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonShowTeamBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelShowTeamBLayout = new javax.swing.GroupLayout(jPanelShowTeamB);
        jPanelShowTeamB.setLayout(jPanelShowTeamBLayout);
        jPanelShowTeamBLayout.setHorizontalGroup(
            jPanelShowTeamBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShowTeamBLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButtonShowTeamB)
                .addGap(68, 68, 68))
        );
        jPanelShowTeamBLayout.setVerticalGroup(
            jPanelShowTeamBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowTeamBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonShowTeamB)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelShowTeamB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelShowTeamB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel14);

        jTabbedPaneA.addTab("تیم میزبان ", jPanel9);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jPanelteamMansA.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelteamMansA.setLayout(new java.awt.GridLayout(0, 1));
        jPanel3.add(jPanelteamMansA);

        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        jPanelPicA.setBackground(new java.awt.Color(0, 0, 0));
        jPanelPicA.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanelPicA.setLayout(new java.awt.GridLayout(1, 0));
        jPanel12.add(jPanelPicA);

        jButton2.setText("ورود لوگو");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton2);

        jTextFieldteamname_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldteamname_1.setText("نام");

        jTextFieldteamCity_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldteamCity_1.setText("شهر");

        jTextFieldteamcoachA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldteamcoachA.setText("مربی");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("مربی تیم");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("شهر تیم");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("نام تیم");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldteamCity_1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldteamname_1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jTextFieldteamcoachA, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldteamname_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldteamCity_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldteamcoachA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelShowTeamA.setBackground(new java.awt.Color(153, 153, 153));

        jToggleButtonShowTeamA.setText("نمایش اسامی");
        jToggleButtonShowTeamA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonShowTeamAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelShowTeamALayout = new javax.swing.GroupLayout(jPanelShowTeamA);
        jPanelShowTeamA.setLayout(jPanelShowTeamALayout);
        jPanelShowTeamALayout.setHorizontalGroup(
            jPanelShowTeamALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowTeamALayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jToggleButtonShowTeamA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelShowTeamALayout.setVerticalGroup(
            jPanelShowTeamALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowTeamALayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jToggleButtonShowTeamA)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jButton1.setText("خواندن فایل اسامی");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelShowTeamA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelShowTeamA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel10);

        jTabbedPaneA.addTab("تیم میهمان ", jPanel3);

        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jTextFieldrefree1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldrefree1.setText("نام");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("داور 1");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("داور 2");

        jTextFieldrefree2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldrefree2.setText("نام");

        jTextFieldrefree3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldrefree3.setText("نام");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("داور 3");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldrefree2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldrefree1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jTextFieldrefree3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldrefree1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldrefree2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldrefree3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelShowrefree.setBackground(new java.awt.Color(153, 153, 153));

        jToggleButtonShowrefree.setText("نمایش داوران");
        jToggleButtonShowrefree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonShowrefreeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelShowrefreeLayout = new javax.swing.GroupLayout(jPanelShowrefree);
        jPanelShowrefree.setLayout(jPanelShowrefreeLayout);
        jPanelShowrefreeLayout.setHorizontalGroup(
            jPanelShowrefreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShowrefreeLayout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(jToggleButtonShowrefree)
                .addGap(75, 75, 75))
        );
        jPanelShowrefreeLayout.setVerticalGroup(
            jPanelShowrefreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowrefreeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jToggleButtonShowrefree)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jPanelShowrefree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(176, 176, 176))
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(175, 175, 175)))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jPanelShowrefree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(307, Short.MAX_VALUE)))
        );

        jPanel11.add(jPanel17);

        jTabbedPaneA.addTab("داورها", jPanel11);

        add(jTabbedPaneA, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonShowIntrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonShowIntrActionPerformed
        // TODO add your handling code here:
        showIntrAction();

    }//GEN-LAST:event_jToggleButtonShowIntrActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ResetTeamData();
        JFileChooser chooser = new JFileChooser(new File("."));
        File f = new File(teamData.getTeamLogoA());
        chooser.setCurrentDirectory(f);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            imagePanelA.drawImage(chooser.getSelectedFile());
            teamData.setTeamLogoA(chooser.getSelectedFile().getPath());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ResetTeamData();
        JFileChooser chooser = new JFileChooser(new File("."));
        File f = new File(teamData.getTeamLogoB());
        chooser.setCurrentDirectory(f);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            imagePanelB.drawImage(chooser.getSelectedFile());
            teamData.setTeamLogoB(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jToggleButtonShowTeamAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonShowTeamAActionPerformed
        // TODO add your handling code here:
        showTeamA();
    }//GEN-LAST:event_jToggleButtonShowTeamAActionPerformed

    private void jToggleButtonShowTeamBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonShowTeamBActionPerformed
        // TODO add your handling code here:
        showTeamB();
    }//GEN-LAST:event_jToggleButtonShowTeamBActionPerformed

    private void jToggleButtonShowrefreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonShowrefreeActionPerformed
        // TODO add your handling code here:
        showREfree();
    }//GEN-LAST:event_jToggleButtonShowrefreeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loadteamData(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        loadteamData(1);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelPicA;
    private javax.swing.JPanel jPanelPicB;
    private javax.swing.JPanel jPanelShowTeamA;
    private javax.swing.JPanel jPanelShowTeamB;
    private javax.swing.JPanel jPanelShowrefree;
    private javax.swing.JPanel jPanellShowIntr;
    private javax.swing.JPanel jPanelteamMansA;
    private javax.swing.JPanel jPanelteamMansB;
    private javax.swing.JTabbedPane jTabbedPaneA;
    private javax.swing.JTextField jTextFieldIntroLine_1;
    private javax.swing.JTextField jTextFieldIntroLine_2;
    private javax.swing.JTextField jTextFieldIntroLine_3;
    private javax.swing.JTextField jTextFieldIntroLine_4;
    private javax.swing.JTextField jTextFieldIntroLine_5;
    private javax.swing.JTextField jTextFieldrefree1;
    private javax.swing.JTextField jTextFieldrefree2;
    private javax.swing.JTextField jTextFieldrefree3;
    private javax.swing.JTextField jTextFieldteamCity_1;
    private javax.swing.JTextField jTextFieldteamCity_2;
    private javax.swing.JTextField jTextFieldteamcoachA;
    private javax.swing.JTextField jTextFieldteamcoachB;
    private javax.swing.JTextField jTextFieldteamname_1;
    private javax.swing.JTextField jTextFieldteamname_2;
    private javax.swing.JToggleButton jToggleButtonShowIntr;
    private javax.swing.JToggleButton jToggleButtonShowTeamA;
    private javax.swing.JToggleButton jToggleButtonShowTeamB;
    private javax.swing.JToggleButton jToggleButtonShowrefree;
    // End of variables declaration//GEN-END:variables

    private void showIntrAction() {
        updateteamdata();
        if (jToggleButtonShowIntr.isSelected()) {
            jPanellShowIntr.setBackground(Color.red);
            jToggleButtonShowIntr.setText("Hide Intro");
            controllCommandSet.showIntroOn();

        } else {
            jPanellShowIntr.setBackground(Color.GRAY);
            jToggleButtonShowIntr.setText("Show Intro");
            controllCommandSet.showIntrooff();
        }
    }

    private void showTeamA() {
        teamData.setShowTeam(0);
        updateteamdata();
        if (jToggleButtonShowTeamA.isSelected()) {
            jPanelShowTeamA.setBackground(Color.red);
            jToggleButtonShowTeamA.setText("Hide Team");
            controllCommandSet.showTeamon();

        } else {
            jPanelShowTeamA.setBackground(Color.GRAY);
            jToggleButtonShowTeamA.setText("Show Team");
            controllCommandSet.showTeamoff();
        }
    }

    private void showTeamB() {
        teamData.setShowTeam(1);
        updateteamdata();
        if (jToggleButtonShowTeamB.isSelected()) {
            jPanelShowTeamB.setBackground(Color.red);
            jToggleButtonShowTeamB.setText("Hide Team");
            controllCommandSet.showTeamon();

        } else {
            jPanelShowTeamB.setBackground(Color.GRAY);
            jToggleButtonShowTeamB.setText("Show Team");
            controllCommandSet.showTeamoff();
        }
    }

    private void initData() {
        ResetTeamData();
        pannel_name_noA = new jPannel_name_no[teamData.getManA().length];
        pannel_name_noB = new jPannel_name_no[teamData.getManB().length];
        jPanelteamMansA.removeAll();
        for (int i = 0; i < pannel_name_noA.length; i++) {
            pannel_name_noA[i] = new jPannel_name_no();
            pannel_name_noA[i].setNameNo(teamData.getManAbyIndex(i).getName(), teamData.getManAbyIndex(i).getNo());
            jPanelteamMansA.add(pannel_name_noA[i]);
        }
        jPanelteamMansB.removeAll();
        for (int i = 0; i < pannel_name_noB.length; i++) {
            pannel_name_noB[i] = new jPannel_name_no();
            pannel_name_noB[i].setNameNo(teamData.getManBbyIndex(i).getName(), teamData.getManBbyIndex(i).getNo());
            jPanelteamMansB.add(pannel_name_noB[i]);
        }

        imagePanelA = new ImagePanel();
        imagePanelB = new ImagePanel();
        imagePanelA.setAddress(teamData.getTeamLogoA());
        imagePanelB.setAddress(teamData.getTeamLogoB());

        jPanelPicA.removeAll();
        jPanelPicB.removeAll();
        jPanelPicA.add(imagePanelA);
        jPanelPicB.add(imagePanelB);

        jTextFieldIntroLine_1.setText(teamData.getLines(0));
        jTextFieldIntroLine_2.setText(teamData.getLines(1));
        jTextFieldIntroLine_3.setText(teamData.getLines(2));
        jTextFieldIntroLine_4.setText(teamData.getLines(3));
        jTextFieldIntroLine_5.setText(teamData.getLines(4));

        jTextFieldteamname_1.setText(teamData.getTeamNameA());
        jTextFieldteamname_2.setText(teamData.getTeamNameB());

        jTextFieldteamCity_1.setText(teamData.getTeamCityA());
        jTextFieldteamCity_2.setText(teamData.getTeamCityB());

        jTextFieldteamcoachA.setText(teamData.getTeamCoachA());
        jTextFieldteamcoachB.setText(teamData.getTeamCoachB());

        jTextFieldrefree1.setText(teamData.getTeamRefree(0));
        jTextFieldrefree2.setText(teamData.getTeamRefree(1));
        jTextFieldrefree3.setText(teamData.getTeamRefree(2));
        
        imagePanelA.redrawImage();
        imagePanelB.redrawImage();
        
        
        updateUI();
    }

    private void ResetTeamData() {
        teamData = controllInterFace.getControolPack().getTeamData();
    }

    private void updateteamdata() {
        String line[] = {"", "", "", "", ""};
        line[0] = jTextFieldIntroLine_1.getText();
        line[1] = jTextFieldIntroLine_2.getText();
        line[2] = jTextFieldIntroLine_3.getText();
        line[3] = jTextFieldIntroLine_4.getText();
        line[4] = jTextFieldIntroLine_5.getText();
        teamData.setLines(line);

        teamData.setTeamNameA(jTextFieldteamname_1.getText());
        teamData.setTeamNameB(jTextFieldteamname_2.getText());

        teamData.setTeamCityA(jTextFieldteamCity_1.getText());
        teamData.setTeamCityB(jTextFieldteamCity_2.getText());

        teamData.setTeamCoachA(jTextFieldteamcoachA.getText());
        teamData.setTeamCoachB(jTextFieldteamcoachB.getText());

        teamData.setTeamRefree(jTextFieldrefree1.getText(), 0);
        teamData.setTeamRefree(jTextFieldrefree2.getText(), 1);
        teamData.setTeamRefree(jTextFieldrefree3.getText(), 2);

        teamData.setTeamLogoA(imagePanelA.getAddress());
        teamData.setTeamLogoB(imagePanelB.getAddress());

        for (int i = 0; i < teamData.getManA().length; i++) {
            teamData.setManNameNoAbyIndex(pannel_name_noA[i].getName(), pannel_name_noA[i].getNo(), i);
            teamData.setManNameNoBbyIndex(pannel_name_noB[i].getName(), pannel_name_noB[i].getNo(), i);
        }

        controllInterFace.updateControlpack();
    }

    private void showREfree() {
        updateteamdata();
        if (jToggleButtonShowrefree.isSelected()) {
            jPanelShowrefree.setBackground(Color.red);
            jToggleButtonShowrefree.setText("Hide refree");
            controllCommandSet.showRefreOn();

        } else {
            jPanelShowrefree.setBackground(Color.GRAY);
            jToggleButtonShowrefree.setText("Show refree");
            controllCommandSet.showRefreOff();
        }
    }

    private void loadteamData(int i) {
        JFileChooser chooser = new JFileChooser(new File("."));
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            new FileManipulatBasket().readTeamName((chooser.getSelectedFile().getPath()), teamData, i);
        }
        initData();
    }
}
