/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controll;

import DataBox.BasketControllData;
import DataBox.ControolPack;
import DataBox.ScoreHistory;
import java.awt.Color;
import java.io.File;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Shayan
 */
public class BasKetballPlay extends javax.swing.JPanel {

    ControllInterFace controllInterFace;
    ControllCommandSet controllCommandSet;
    ScoreHistory scoreHistory;
    JTextField jtextscoreHistory1[], jtextscoreHistory2[];
    BasketControllData basketControllData;
    String basketControllDataFilename;
    String teamPic[];
    boolean actionTeamColor;

    /**
     * Creates new form BasKetballPlay
     */
    public BasKetballPlay(ControllInterFace controllInterFace) {

        initComponents();

        this.controllInterFace = controllInterFace;
        controllCommandSet = controllInterFace.getControllCommandSet();
        scoreHistory = new ScoreHistory();

        jtextscoreHistory1 = new JTextField[scoreHistory.getMaxhistory()];
        jtextscoreHistory2 = new JTextField[scoreHistory.getMaxhistory()];
        for (int i = 0; i < scoreHistory.getMaxhistory(); i++) {
            jtextscoreHistory1[i] = new JTextField(" ");
            jtextscoreHistory2[i] = new JTextField(" ");
            jPanel_history1.add(jtextscoreHistory1[i]);
            jPanel_history2.add(jtextscoreHistory2[i]);
        }

        basketControllDataFilename = "seting\\baskCoDaFi.json";
        teamPic = new String[2];

        loadbaskControldataFile();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupQuarter = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jToggleButtoncrunch_show = new javax.swing.JToggleButton();
        jButton12 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButtonColor3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButtonColor1 = new javax.swing.JButton();
        jTextFieldCountryTop = new javax.swing.JTextField();
        jTextField_point_1 = new javax.swing.JTextField();
        jButton_min_1 = new javax.swing.JButton();
        jButton_Plus_1 = new javax.swing.JButton();
        jButton_Plus_3 = new javax.swing.JButton();
        jButton_Plus_4 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButtonColor2 = new javax.swing.JButton();
        jTextFieldCountryBot = new javax.swing.JTextField();
        jTextField_point_2 = new javax.swing.JTextField();
        jButton_min_2 = new javax.swing.JButton();
        jButton_Plus_2 = new javax.swing.JButton();
        jButton_Plus_5 = new javax.swing.JButton();
        jButton_Plus_6 = new javax.swing.JButton();
        jPanel38 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSpinnerTeamTopError = new javax.swing.JSpinner();
        jButton_min_3 = new javax.swing.JButton();
        jButton_Plus_7 = new javax.swing.JButton();
        jButton_Plus_9 = new javax.swing.JButton();
        jToggleButtonShowTeamNameA = new javax.swing.JToggleButton();
        jPanel12 = new javax.swing.JPanel();
        jSpinnerTeamBotError = new javax.swing.JSpinner();
        jButton_min_4 = new javax.swing.JButton();
        jButton_Plus_8 = new javax.swing.JButton();
        jButton_Plus_10 = new javax.swing.JButton();
        jToggleButtonShowTeamNameB = new javax.swing.JToggleButton();
        jPanel26 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanelQuarterName = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jTextFieldSetTop1 = new javax.swing.JTextField();
        jTextFieldSetTop2 = new javax.swing.JTextField();
        jTextFieldSetTop3 = new javax.swing.JTextField();
        jTextFieldSetTop4 = new javax.swing.JTextField();
        jTextFieldSetTop5 = new javax.swing.JTextField();
        jPanel33 = new javax.swing.JPanel();
        jTextFieldSetbot1 = new javax.swing.JTextField();
        jTextFieldSetbot2 = new javax.swing.JTextField();
        jTextFieldSetbot3 = new javax.swing.JTextField();
        jTextFieldSetbot4 = new javax.swing.JTextField();
        jTextFieldSetbot5 = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jPanel35 = new javax.swing.JPanel();
        jToggleButtonExpandContract = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jToggleButtonPlayByPlay = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel_history1 = new javax.swing.JPanel();
        jPanel_history2 = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 2));

        jPanel7.setLayout(new java.awt.GridLayout(2, 2));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new java.awt.GridLayout(4, 1));

        jPanel37.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setText("LineScore");
        jPanel37.add(jLabel3);

        jToggleButtoncrunch_show.setText("Show");
        jToggleButtoncrunch_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtoncrunch_showActionPerformed(evt);
            }
        });
        jPanel37.add(jToggleButtoncrunch_show);

        jButton12.setText("Reset Set");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel37.add(jButton12);

        jPanel5.add(jPanel37);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jButtonColor3.setBackground(new java.awt.Color(0, 0, 0));
        jButtonColor3.setForeground(new java.awt.Color(0, 0, 51));
        jButtonColor3.setText("color");
        jButtonColor3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonColor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonColor3);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Team");
        jPanel8.add(jLabel6);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Point");
        jPanel8.add(jLabel2);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("min");
        jPanel8.add(jLabel7);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("add");
        jPanel8.add(jLabel8);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("add");
        jPanel8.add(jLabel14);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("add");
        jPanel8.add(jLabel15);

        jPanel5.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jButtonColor1.setText("*");
        jButtonColor1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor1ActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonColor1);

        jTextFieldCountryTop.setText("IRN");
        jTextFieldCountryTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCountryTopActionPerformed(evt);
            }
        });
        jPanel9.add(jTextFieldCountryTop);

        jTextField_point_1.setText("0");
        jTextField_point_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_point_1ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField_point_1);

        jButton_min_1.setText("-");
        jButton_min_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_min_1ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton_min_1);

        jButton_Plus_1.setText("+");
        jButton_Plus_1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_Plus_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Plus_1ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton_Plus_1);

        jButton_Plus_3.setText("+2");
        jButton_Plus_3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_Plus_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Plus_3ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton_Plus_3);

        jButton_Plus_4.setText("+3");
        jButton_Plus_4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_Plus_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Plus_4ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton_Plus_4);

        jPanel5.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        jButtonColor2.setText("*");
        jButtonColor2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor2ActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonColor2);

        jTextFieldCountryBot.setText("USA");
        jTextFieldCountryBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCountryBotActionPerformed(evt);
            }
        });
        jPanel10.add(jTextFieldCountryBot);

        jTextField_point_2.setText("0");
        jTextField_point_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_point_2ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField_point_2);

        jButton_min_2.setText("-");
        jButton_min_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_min_2ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton_min_2);

        jButton_Plus_2.setText("+");
        jButton_Plus_2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_Plus_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Plus_2ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton_Plus_2);

        jButton_Plus_5.setText("+2");
        jButton_Plus_5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_Plus_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Plus_5ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton_Plus_5);

        jButton_Plus_6.setText("+3");
        jButton_Plus_6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_Plus_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Plus_6ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton_Plus_6);

        jPanel5.add(jPanel10);

        jPanel7.add(jPanel5);

        jPanel38.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton1);

        jPanel2.add(jPanel11);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Foul");
        jPanel3.add(jLabel1);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("mies");
        jPanel3.add(jLabel5);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("add");
        jPanel3.add(jLabel9);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("pic");
        jPanel3.add(jLabel10);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("name");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel11);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));
        jPanel4.add(jSpinnerTeamTopError);

        jButton_min_3.setText("-");
        jButton_min_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_min_3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_min_3);

        jButton_Plus_7.setText("+");
        jButton_Plus_7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_Plus_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Plus_7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_Plus_7);

        jButton_Plus_9.setText("Get");
        jButton_Plus_9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_Plus_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Plus_9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_Plus_9);

        jToggleButtonShowTeamNameA.setText("Show");
        jToggleButtonShowTeamNameA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonShowTeamNameAActionPerformed(evt);
            }
        });
        jPanel4.add(jToggleButtonShowTeamNameA);

        jPanel2.add(jPanel4);

        jPanel12.setLayout(new java.awt.GridLayout(1, 0));
        jPanel12.add(jSpinnerTeamBotError);

        jButton_min_4.setText("-");
        jButton_min_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_min_4ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton_min_4);

        jButton_Plus_8.setText("+");
        jButton_Plus_8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_Plus_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Plus_8ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton_Plus_8);

        jButton_Plus_10.setText("Get");
        jButton_Plus_10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_Plus_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Plus_10ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton_Plus_10);

        jToggleButtonShowTeamNameB.setText("Show");
        jToggleButtonShowTeamNameB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonShowTeamNameBActionPerformed(evt);
            }
        });
        jPanel12.add(jToggleButtonShowTeamNameB);

        jPanel2.add(jPanel12);

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 74, Short.MAX_VALUE))
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel38);

        jPanel26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel26.setLayout(new java.awt.GridLayout(1, 0));

        jPanel31.setMinimumSize(new java.awt.Dimension(150, 100));
        jPanel31.setPreferredSize(new java.awt.Dimension(140, 60));
        jPanel31.setLayout(new java.awt.GridLayout(4, 1));

        jPanelQuarterName.setLayout(new java.awt.GridLayout(1, 0));
        jPanel31.add(jPanelQuarterName);

        jPanel32.setLayout(new java.awt.GridLayout(1, 0));

        jTextFieldSetTop1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSetTop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSetTop1ActionPerformed(evt);
            }
        });
        jPanel32.add(jTextFieldSetTop1);

        jTextFieldSetTop2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel32.add(jTextFieldSetTop2);

        jTextFieldSetTop3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel32.add(jTextFieldSetTop3);

        jTextFieldSetTop4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSetTop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSetTop4ActionPerformed(evt);
            }
        });
        jPanel32.add(jTextFieldSetTop4);

        jTextFieldSetTop5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSetTop5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSetTop5ActionPerformed(evt);
            }
        });
        jPanel32.add(jTextFieldSetTop5);

        jPanel31.add(jPanel32);

        jPanel33.setLayout(new java.awt.GridLayout(1, 0));

        jTextFieldSetbot1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel33.add(jTextFieldSetbot1);

        jTextFieldSetbot2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel33.add(jTextFieldSetbot2);

        jTextFieldSetbot3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel33.add(jTextFieldSetbot3);

        jTextFieldSetbot4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSetbot4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSetbot4ActionPerformed(evt);
            }
        });
        jPanel33.add(jTextFieldSetbot4);

        jTextFieldSetbot5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSetbot5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSetbot5ActionPerformed(evt);
            }
        });
        jPanel33.add(jTextFieldSetbot5);

        jPanel31.add(jPanel33);

        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        buttonGroupQuarter.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setActionCommand("0");
        jRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel15.add(jRadioButton1);

        buttonGroupQuarter.add(jRadioButton2);
        jRadioButton2.setActionCommand("1");
        jRadioButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel15.add(jRadioButton2);

        buttonGroupQuarter.add(jRadioButton3);
        jRadioButton3.setActionCommand("2");
        jRadioButton3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel15.add(jRadioButton3);

        buttonGroupQuarter.add(jRadioButton4);
        jRadioButton4.setActionCommand("3");
        jRadioButton4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel15.add(jRadioButton4);

        buttonGroupQuarter.add(jRadioButton5);
        jRadioButton5.setActionCommand("4");
        jRadioButton5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel15.add(jRadioButton5);

        jPanel31.add(jPanel15);

        jPanel26.add(jPanel31);

        jPanel35.setPreferredSize(new java.awt.Dimension(90, 60));
        jPanel35.setLayout(new java.awt.GridLayout(0, 1));

        jToggleButtonExpandContract.setText("Expand");
        jToggleButtonExpandContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonExpandContractActionPerformed(evt);
            }
        });
        jPanel35.add(jToggleButtonExpandContract);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jButton2.setText("Q name");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);

        jButton3.setText("Clear Q");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);

        jPanel35.add(jPanel6);

        jPanel26.add(jPanel35);

        jPanel7.add(jPanel26);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel39.setLayout(new java.awt.GridLayout(0, 1));

        jPanel23.setLayout(new java.awt.GridLayout(1, 0));

        jToggleButtonPlayByPlay.setText("Show");
        jToggleButtonPlayByPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPlayByPlayActionPerformed(evt);
            }
        });
        jPanel23.add(jToggleButtonPlayByPlay);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Play By Play");
        jPanel23.add(jLabel4);

        jPanel39.add(jPanel23);

        jPanel_history1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_history1.setLayout(new java.awt.GridLayout(1, 0));
        jPanel39.add(jPanel_history1);

        jPanel_history2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_history2.setLayout(new java.awt.GridLayout(1, 0));
        jPanel39.add(jPanel_history2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel39, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jPanel39, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        jPanel7.add(jPanel1);

        add(jPanel7);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonPlayByPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPlayByPlayActionPerformed
        // TODO add your handling code here:
        if (jToggleButtonPlayByPlay.isSelected()) {
//            controllCommandSet.testShow();
        } else {
//            controllCommandSet.testHide();
        }
    }//GEN-LAST:event_jToggleButtonPlayByPlayActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        resetSet();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        controllInterFace.updateControlpack();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButtoncrunch_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtoncrunch_showActionPerformed
        // TODO add your handling code here:
//        System.out.println("control time in action 1 "+controllInterFace.getControolPack().getTimePack().getSec24());
        if (jToggleButtoncrunch_show.isSelected()) {
            jToggleButtoncrunch_show.setText("Hide");
            controllCommandSet.errorShow(getFoulTop(), getFoulBot());
            controllInterFace.getControolPack().setErrorVis(true);
//             System.out.println("control time in action 2 "+controllInterFace.getControolPack().getTimePack().getSec24());
            controllCommandSet.teamNameShow(jToggleButtonShowTeamNameA.isSelected(), jToggleButtonShowTeamNameB.isSelected());
//            System.out.println("control time in action 3 "+controllInterFace.getControolPack().getTimePack().getSec24());
            if (controllInterFace.getControolPack().getTimeCoverVis()) {
                controllCommandSet.timersCoverShow();
            } else {
                controllCommandSet.timersCoverHide();
            }
//            System.out.println("control time in action 4 "+controllInterFace.getControolPack().getTimePack().getSec24());
            controllCommandSet.Linescore_show();
//            System.out.println("control time in action 5 "+controllInterFace.getControolPack().getTimePack().getSec24());
        } else {
            jToggleButtoncrunch_show.setText("Show");
//            controllCommandSet.errorHide();
            controllInterFace.getControolPack().setErrorVis(false);
//            controllCommandSet.timersCoverHide();
            controllCommandSet.Linescore_Hide();
            controllCommandSet.errorHide();
        }
//        controllInterFace.updateControlpack();
    }//GEN-LAST:event_jToggleButtoncrunch_showActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        renameQuarterName();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButtonExpandContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonExpandContractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonExpandContractActionPerformed

    private void jButton_Plus_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Plus_6ActionPerformed
        // TODO add your handling code here:
        teamB_Point(3);
    }//GEN-LAST:event_jButton_Plus_6ActionPerformed

    private void jButton_Plus_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Plus_5ActionPerformed
        // TODO add your handling code here:
        teamB_Point(2);
    }//GEN-LAST:event_jButton_Plus_5ActionPerformed

    private void jButton_Plus_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Plus_2ActionPerformed
        // TODO add your handling code here:
        teamB_Point(1);
    }//GEN-LAST:event_jButton_Plus_2ActionPerformed

    private void jButton_min_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_min_2ActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(jTextField_point_2.getText());
        if (x > 0) {
            x--;
            scoreHistory.removescore();
            updatescoreHistory();
        }
        jTextField_point_2.setText(String.valueOf(x));
        //        buttonGroupSrvs.clearSelection();
        controllInterFace.updateControlpack();
    }//GEN-LAST:event_jButton_min_2ActionPerformed

    private void jTextField_point_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_point_2ActionPerformed
        // TODO add your handling code here:
        controllInterFace.updateControlpack();
    }//GEN-LAST:event_jTextField_point_2ActionPerformed

    private void jTextFieldCountryBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCountryBotActionPerformed
        // TODO add your handling code here:
        controllInterFace.updateControlpack();
    }//GEN-LAST:event_jTextFieldCountryBotActionPerformed

    private void jButtonColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor2ActionPerformed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Choose a Color", jButtonColor2.getForeground());
        jButtonColor2.setBackground(c);
        actionTeamColor = true;
        controllInterFace.updateControlpack();
        actionTeamColor = false;
    }//GEN-LAST:event_jButtonColor2ActionPerformed

    private void jButton_Plus_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Plus_4ActionPerformed
        // TODO add your handling code here:
        teamA_Point(3);
    }//GEN-LAST:event_jButton_Plus_4ActionPerformed

    private void jButton_Plus_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Plus_3ActionPerformed
        // TODO add your handling code here:
        teamA_Point(2);
    }//GEN-LAST:event_jButton_Plus_3ActionPerformed

    private void jButton_Plus_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Plus_1ActionPerformed
        // TODO add your handling code here:
        teamA_Point(1);
    }//GEN-LAST:event_jButton_Plus_1ActionPerformed

    private void jButton_min_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_min_1ActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(jTextField_point_1.getText());
        if (x > 0) {
            x--;
            scoreHistory.removescore();
            updatescoreHistory();
        }
        jTextField_point_1.setText(String.valueOf(x));
        //        buttonGroupSrvs.clearSelection();
        controllInterFace.updateControlpack();
    }//GEN-LAST:event_jButton_min_1ActionPerformed

    private void jTextField_point_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_point_1ActionPerformed
        // TODO add your handling code here:
        controllInterFace.updateControlpack();
    }//GEN-LAST:event_jTextField_point_1ActionPerformed

    private void jTextFieldCountryTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCountryTopActionPerformed
        // TODO add your handling code here:
        if (controllInterFace.isNewsha()) {
            controllInterFace.updateControlpack();
        }
    }//GEN-LAST:event_jTextFieldCountryTopActionPerformed

    private void jButtonColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor1ActionPerformed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Choose a Color", jButtonColor1.getForeground());
        jButtonColor1.setBackground(c);
        actionTeamColor = true;
        controllInterFace.updateControlpack();
        actionTeamColor = false;

    }//GEN-LAST:event_jButtonColor1ActionPerformed

    private void jButtonColor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonColor3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextFieldSetTop1.setText("");
        jTextFieldSetTop2.setText("");
        jTextFieldSetTop3.setText("");
        jTextFieldSetTop4.setText("");
        jTextFieldSetTop5.setText("");
        jTextFieldSetbot1.setText("");
        jTextFieldSetbot2.setText("");
        jTextFieldSetbot3.setText("");
        jTextFieldSetbot4.setText("");
        jTextFieldSetbot5.setText("");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldSetbot5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSetbot5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSetbot5ActionPerformed

    private void jTextFieldSetbot4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSetbot4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSetbot4ActionPerformed

    private void jTextFieldSetTop5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSetTop5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSetTop5ActionPerformed

    private void jTextFieldSetTop4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSetTop4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSetTop4ActionPerformed

    private void jTextFieldSetTop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSetTop1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSetTop1ActionPerformed

    private void jButton_min_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_min_3ActionPerformed
        // TODO add your handling code here:
        int x = 0;
        x = Integer.parseInt(jSpinnerTeamTopError.getValue().toString());
        if (x > 0) {
            jSpinnerTeamTopError.setValue(--x);
        } else {
            JOptionPane.showMessageDialog(null, "خطاها کمتر از حد مجاز");
        }
        controllInterFace.updateControlpack();
    }//GEN-LAST:event_jButton_min_3ActionPerformed

    private void jButton_Plus_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Plus_7ActionPerformed
        // TODO add your handling code here:
        int x = 0;
        x = Integer.parseInt(jSpinnerTeamTopError.getValue().toString());
        if (x < 5) {
            jSpinnerTeamTopError.setValue(++x);
        } else {
            JOptionPane.showMessageDialog(null, "خطاها بیشتر از حد مجاز");
        }
        controllInterFace.updateControlpack();
    }//GEN-LAST:event_jButton_Plus_7ActionPerformed

    private void jButton_min_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_min_4ActionPerformed
        // TODO add your handling code here:
        int x = 0;
        x = Integer.parseInt(jSpinnerTeamBotError.getValue().toString());
        if (x > 0) {
            jSpinnerTeamBotError.setValue(--x);
        } else {
            JOptionPane.showMessageDialog(null, "خطاها کمتر از حد مجاز");
        }
        controllInterFace.updateControlpack();
    }//GEN-LAST:event_jButton_min_4ActionPerformed

    private void jButton_Plus_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Plus_8ActionPerformed
        // TODO add your handling code here:
        int x = 0;
        x = Integer.parseInt(jSpinnerTeamBotError.getValue().toString());
        if (x < 5) {
            jSpinnerTeamBotError.setValue(++x);
        } else {
            JOptionPane.showMessageDialog(null, "خطاها بیشتر از حد مجاز");
        }
        controllInterFace.updateControlpack();
    }//GEN-LAST:event_jButton_Plus_8ActionPerformed

    private void jButton_Plus_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Plus_9ActionPerformed
        // TODO add your handling code here:
        getTeamPic(0);
    }//GEN-LAST:event_jButton_Plus_9ActionPerformed

    private void jButton_Plus_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Plus_10ActionPerformed
        // TODO add your handling code here:
        getTeamPic(1);
    }//GEN-LAST:event_jButton_Plus_10ActionPerformed

    private void jToggleButtonShowTeamNameAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonShowTeamNameAActionPerformed
        // TODO add your handling code here:
        setShowTeamNames();
    }//GEN-LAST:event_jToggleButtonShowTeamNameAActionPerformed

    private void jToggleButtonShowTeamNameBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonShowTeamNameBActionPerformed
        // TODO add your handling code here:
        setShowTeamNames();
    }//GEN-LAST:event_jToggleButtonShowTeamNameBActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.ButtonGroup buttonGroupQuarter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    protected javax.swing.JButton jButtonColor1;
    protected javax.swing.JButton jButtonColor2;
    private javax.swing.JButton jButtonColor3;
    private javax.swing.JButton jButton_Plus_1;
    private javax.swing.JButton jButton_Plus_10;
    private javax.swing.JButton jButton_Plus_2;
    private javax.swing.JButton jButton_Plus_3;
    private javax.swing.JButton jButton_Plus_4;
    private javax.swing.JButton jButton_Plus_5;
    private javax.swing.JButton jButton_Plus_6;
    private javax.swing.JButton jButton_Plus_7;
    private javax.swing.JButton jButton_Plus_8;
    private javax.swing.JButton jButton_Plus_9;
    private javax.swing.JButton jButton_min_1;
    private javax.swing.JButton jButton_min_2;
    private javax.swing.JButton jButton_min_3;
    private javax.swing.JButton jButton_min_4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    protected javax.swing.JPanel jPanelQuarterName;
    private javax.swing.JPanel jPanel_history1;
    private javax.swing.JPanel jPanel_history2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JSpinner jSpinnerTeamBotError;
    private javax.swing.JSpinner jSpinnerTeamTopError;
    protected javax.swing.JTextField jTextFieldCountryBot;
    protected javax.swing.JTextField jTextFieldCountryTop;
    protected javax.swing.JTextField jTextFieldSetTop1;
    protected javax.swing.JTextField jTextFieldSetTop2;
    protected javax.swing.JTextField jTextFieldSetTop3;
    protected javax.swing.JTextField jTextFieldSetTop4;
    protected javax.swing.JTextField jTextFieldSetTop5;
    protected javax.swing.JTextField jTextFieldSetbot1;
    protected javax.swing.JTextField jTextFieldSetbot2;
    protected javax.swing.JTextField jTextFieldSetbot3;
    protected javax.swing.JTextField jTextFieldSetbot4;
    protected javax.swing.JTextField jTextFieldSetbot5;
    protected javax.swing.JTextField jTextField_point_1;
    protected javax.swing.JTextField jTextField_point_2;
    private javax.swing.JToggleButton jToggleButtonExpandContract;
    private javax.swing.JToggleButton jToggleButtonPlayByPlay;
    private javax.swing.JToggleButton jToggleButtonShowTeamNameA;
    private javax.swing.JToggleButton jToggleButtonShowTeamNameB;
    private javax.swing.JToggleButton jToggleButtoncrunch_show;
    // End of variables declaration//GEN-END:variables

    private void resetSet() {
        jTextField_point_1.setText("0");
        jTextField_point_2.setText("0");
        jSpinnerTeamTopError.setValue(0);
        jSpinnerTeamBotError.setValue(0);
        scoreHistory.reset();
        updatescoreHistory();
    }

    private void updatescoreHistory() {
        for (int i = 0; i < scoreHistory.getMaxhistory(); i++) {
            jtextscoreHistory1[i].setText(scoreHistory.getscore1(i));
            jtextscoreHistory2[i].setText(scoreHistory.getscore2(i));
        }
    }

    private void teamB_Point(int i) {
        int x;
        try {
            x = Integer.parseInt(jTextField_point_2.getText());
        } catch (Exception e) {
            x = 0;
        }
        controllInterFace.getControolPack().getGameData().setPointOldBot(x);
        x += i;
        scoreHistory.addscores(0, x);
        controllInterFace.getControolPack().getGameData().setPointBot(x);
        updatescoreHistory();
        jTextField_point_2.setText(String.valueOf(x));
        controllCommandSet.teamPointAddB(i);
//        controllInterFace.updateControlpack();
    }

    private void teamA_Point(int i) {

        int x;
        try {
            x = Integer.parseInt(jTextField_point_1.getText());
        } catch (Exception e) {
            x = 0;
        }
        controllInterFace.getControolPack().getGameData().setPointOldTop(x);
        x += i;
        controllInterFace.getControolPack().getGameData().setPointTop(x);
        scoreHistory.addscores(x, 0);
        updatescoreHistory();
        jTextField_point_1.setText(String.valueOf(x));

        controllCommandSet.teamPointAddA(i);
//        controllInterFace.updateControlpack();
    }

    private void loadbaskControldataFile() {
        basketControllData = (BasketControllData) new FileManipulat().loadBasketControllData(basketControllDataFilename);
        jPanelQuarterName.removeAll();
        for (int i = 0; i < basketControllData.getQmax(); i++) {
            jPanelQuarterName.add(new JLabel(basketControllData.getQuName(i)));
        }
        jToggleButtonShowTeamNameA.setSelected(basketControllData.getShowTeamName()[0]);
        jToggleButtonShowTeamNameB.setSelected(basketControllData.getShowTeamName()[1]);
//        jTextField_point_1.setText(basketControllData.);
        updateUI();
    }

    private void savvebaskControldataFile() {

        new FileManipulat().saveObject(basketControllDataFilename, basketControllData);

    }

    private void renameQuarterName() {
        if (buttonGroupQuarter.getSelection() != null) {
            int x = Integer.parseInt((buttonGroupQuarter.getSelection()).getActionCommand());
            String st = JOptionPane.showInputDialog("Enter quarter " + x + " Name :");
            if (st != null) {
                if (!st.equals("")) {
                    basketControllData.setQuName(st, x);
                }
                savvebaskControldataFile();
                loadbaskControldataFile();
            } else {
                JOptionPane.showMessageDialog(null, "نام معتبری وارد نکردی");
            }
        } else {
            JOptionPane.showMessageDialog(null, "نخست کوارتر را انتخاب کن");
        }
    }

    public Color getcolor1() {
        return jButtonColor1.getBackground();
    }

    public Color getcolor2() {
        return jButtonColor2.getBackground();
    }

    public int getTeamTopPOint() {
        int x = 0;
        x = Integer.parseInt(jTextField_point_1.getText());
        return x;
    }

    public int getTeamBotPOint() {
        int x = 0;
        x = Integer.parseInt(jTextField_point_2.getText());
        return x;
    }

    public String getTeamTopName() {
        return jTextFieldCountryTop.getText();
    }

    public String getTeamBotName() {
        return jTextFieldCountryBot.getText();
    }

    public String[] getqUpointsTop() {
        String x[] = {"", "", "", "", ""};
        x[0] = jTextFieldSetTop1.getText();
        x[1] = jTextFieldSetTop2.getText();
        x[2] = jTextFieldSetTop3.getText();
        x[3] = jTextFieldSetTop4.getText();
        x[4] = jTextFieldSetTop5.getText();
        return x;
    }

    public String[] getqUpointsBot() {
        String x[] = {"", "", "", "", ""};
        x[0] = jTextFieldSetTop1.getText();
        x[1] = jTextFieldSetTop2.getText();
        x[2] = jTextFieldSetTop3.getText();
        x[3] = jTextFieldSetTop4.getText();
        x[4] = jTextFieldSetTop5.getText();
        return x;
    }

    public String getquName() {
        String temp = "q1";
        int x = 0;
        if (buttonGroupQuarter.getSelection() != null) {
            x = Integer.parseInt((buttonGroupQuarter.getSelection()).getActionCommand());
            temp = basketControllData.getQuName(x);
        }
        return temp;
    }

    private void getTeamPic(int i) {

        JFileChooser chooser = new JFileChooser(new File("*.png"));
        File f = new File(basketControllData.getPath());
        chooser.setCurrentDirectory(f);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            {
                basketControllData.setPath(chooser.getSelectedFile().getPath());
                teamPic[i] = chooser.getSelectedFile().getPath();
                controllInterFace.updateControlpack();
                savvebaskControldataFile();

            }
        }
    }

    void setLoadeddata(ControolPack controolPack) {
        jButtonColor1.setBackground(controolPack.getGameData().getColorTop());
        jButtonColor2.setBackground(controolPack.getGameData().getColorBot());
        jTextFieldCountryTop.setText(controolPack.getGameData().getTeamTopName());
        jTextFieldCountryBot.setText(controolPack.getGameData().getTeamBotName());
        
jTextField_point_1.setText(String.valueOf(controolPack.getGameData().getPointTop()));
jTextField_point_2.setText(String.valueOf(controolPack.getGameData().getPointBot()));
jSpinnerTeamTopError.setValue(controolPack.getGameData().getFoulTop());
jSpinnerTeamBotError.setValue(controolPack.getGameData().getFoulBot());


        teamPic = controolPack.getGameData().getTeamPic();

    }

    int getFoulTop() {
        int x = 0;
        x = Integer.parseInt(jSpinnerTeamTopError.getValue().toString());
        return x;
    }

    int getFoulBot() {
        int x = 0;
        x = Integer.parseInt(jSpinnerTeamBotError.getValue().toString());
        return x;
    }

    public boolean isActionTeamColor() {
        return actionTeamColor;
    }

    public Color[] getTeamColor() {
        Color c[] = new Color[2];
        c[0] = jButtonColor1.getBackground();
        c[1] = jButtonColor2.getBackground();
        return c;
    }

    private void setShowTeamNames() {
        controllCommandSet.teamNameShow(jToggleButtonShowTeamNameA.isSelected(), jToggleButtonShowTeamNameB.isSelected());
        basketControllData.setShowTeamName(jToggleButtonShowTeamNameA.isSelected(), jToggleButtonShowTeamNameB.isSelected());
        savvebaskControldataFile();

    }
}
