/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controll;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author shayan
 */
public class DimPanel extends javax.swing.JPanel {

    /**
     * Creates new form DimPanel
     */
    SettingInterface settingInterface;
    boolean newsha;

    public DimPanel(SettingInterface settingInterface) {
        this.settingInterface = settingInterface;
        initComponents();
        newsha = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelState1 = new javax.swing.JPanel();
        jSpinnerx1 = new javax.swing.JSpinner();
        jSpinnery1 = new javax.swing.JSpinner();
        jSpinnerh1 = new javax.swing.JSpinner();
        jSpinnerw1 = new javax.swing.JSpinner();
        jButtonColor1 = new javax.swing.JButton();
        jButtonStrokColor1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerFrame = new javax.swing.JSpinner();
        jSliderOpac = new javax.swing.JSlider();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();

        jPanelState1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSpinnerx1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerx1StateChanged(evt);
            }
        });
        jPanelState1.add(jSpinnerx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 75, -1));

        jSpinnery1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnery1StateChanged(evt);
            }
        });
        jPanelState1.add(jSpinnery1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 75, -1));

        jSpinnerh1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerh1StateChanged(evt);
            }
        });
        jPanelState1.add(jSpinnerh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 79, -1));

        jSpinnerw1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerw1StateChanged(evt);
            }
        });
        jPanelState1.add(jSpinnerw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 79, -1));

        jButtonColor1.setText("Color");
        jButtonColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor1ActionPerformed(evt);
            }
        });
        jPanelState1.add(jButtonColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 75, -1));

        jButtonStrokColor1.setText("Strok Col");
        jButtonStrokColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStrokColor1ActionPerformed(evt);
            }
        });
        jPanelState1.add(jButtonStrokColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel2.setText("Opac");
        jPanelState1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel1.setText("Position");
        jPanelState1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setText("Size");
        jPanelState1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel4.setText("motion_f");
        jPanelState1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jSpinnerFrame.setRequestFocusEnabled(false);
        jSpinnerFrame.setValue(15);
        jPanelState1.add(jSpinnerFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 80, -1));

        jSliderOpac.setMaximum(255);
        jSliderOpac.setValue(255);
        jSliderOpac.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderOpacStateChanged(evt);
            }
        });
        jPanelState1.add(jSliderOpac, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 150, -1));
        jPanelState1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 60, -1));
        jPanelState1.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("a");
        jPanelState1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 20, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelState1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelState1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerx1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerx1StateChanged
        // TODO add your handling cod here:
        updatetop();
    }//GEN-LAST:event_jSpinnerx1StateChanged

    private void jSpinnery1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnery1StateChanged
        // TODO add your handling code here:
        updatetop();
    }//GEN-LAST:event_jSpinnery1StateChanged

    private void jSpinnerh1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerh1StateChanged
        // TODO add your handling code here:
        updatetop();
    }//GEN-LAST:event_jSpinnerh1StateChanged

    private void jSpinnerw1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerw1StateChanged
        // TODO add your handling code here:
        updatetop();
    }//GEN-LAST:event_jSpinnerw1StateChanged

    private void jButtonColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor1ActionPerformed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Choose a Color", jButtonColor1.getForeground());
        if (c != null) {
            jButtonColor1.setForeground(c);
            updatetop();
        }
    }//GEN-LAST:event_jButtonColor1ActionPerformed

    private void jButtonStrokColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStrokColor1ActionPerformed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Choose a Color", jButtonStrokColor1.getForeground());
        if (c != null) {
            jButtonStrokColor1.setForeground(c);
            updatetop();
        }
    }//GEN-LAST:event_jButtonStrokColor1ActionPerformed

    private void jSliderOpacStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderOpacStateChanged
        // TODO add your handling code here:
        updatetop();

    }//GEN-LAST:event_jSliderOpacStateChanged
    public int[] getdims() {
        int[] x = new int[4];
        x[0] = Integer.parseInt(jSpinnerx1.getValue().toString());
        x[1] = Integer.parseInt(jSpinnery1.getValue().toString());
        x[2] = Integer.parseInt(jSpinnerw1.getValue().toString());
        x[3] = Integer.parseInt(jSpinnerh1.getValue().toString());
        return x;
    }

    public void setdim(int x, int y, int w, int h) {        
        jSpinnerx1.setValue(x);
        jSpinnery1.setValue(y);
        jSpinnerw1.setValue(w);
        jSpinnerh1.setValue(h);

    }

    public void setdims(int x[]) {
        jSpinnerx1.setValue(x[0]);
        jSpinnery1.setValue(x[1]);
        jSpinnerw1.setValue(x[2]);
        jSpinnerh1.setValue(x[3]);

    }

    public Color getColor1() {
        return jButtonColor1.getForeground();
    }

    public void setColor(Color jButtonColor1) {
        this.jButtonColor1.setForeground(jButtonColor1);
    }

    public Color getStrokColor1() {
        return jButtonStrokColor1.getForeground();
    }

    public void setStrokColor1(Color jButtonStrokColor1) {
        this.jButtonStrokColor1.setForeground(jButtonStrokColor1);
    }

    public int getOpacity() {
        return jSliderOpac.getValue();
    }

    public void setOpacity(int jSlider1) {
        this.jSliderOpac.setValue(jSlider1);
    }

    public int getFrame() {
        return Integer.parseInt(jSpinnerFrame.getValue().toString());
    }

    public void setFrame(int f) {
        this.jSpinnerFrame.setValue(f);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonColor1;
    private javax.swing.JButton jButtonStrokColor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelState1;
    private javax.swing.JSlider jSliderOpac;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinnerFrame;
    private javax.swing.JSpinner jSpinnerh1;
    private javax.swing.JSpinner jSpinnerw1;
    private javax.swing.JSpinner jSpinnerx1;
    private javax.swing.JSpinner jSpinnery1;
    // End of variables declaration//GEN-END:variables

    private void updatetop() {
        if (newsha) {
            newsha=false;
            settingInterface.dimupdateSetting();
            newsha=true;
        }
    }

    public boolean isNewsha() {
        return newsha;
    }

    public void setNewsha(boolean newsha) {
        this.newsha = newsha;
    }

}
