/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controll;

import DataBox.Database;
import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author shayan
 */
public class Jpaneldata1 extends javax.swing.JPanel {

    /**
     * Creates new form jpaneldata1
     */
    public Jpaneldata1() {
        initComponents();
        newsha = false;
        database = new Database();
        database = load();

        newsha = true;        
           imagePanel = new ImagePanel();
     

    }
     ImagePanel imagePanel ;
    boolean newsha;
    Database database;
    String datafile = "seting\\datafile.json";
//    koshtiRoundPack roundDataCurrent, roundDataNexxt;
//
//    
//    public koshtiRoundPack getRoundDataCurrent() {
//        return roundDataCurrent;
//    }
//
//    public void setRoundDataCurrent(koshtiRoundPack roundDataCurrent) {
//        this.roundDataCurrent = roundDataCurrent;
//    }
//
//    public koshtiRoundPack getRoundDataNexxt() {
//        return roundDataNexxt;
//    }
//
//    public void setRoundDataNexxt(koshtiRoundPack roundDataNexxt) {
//        this.roundDataNexxt = roundDataNexxt;
//    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new java.awt.GridLayout(1, 0));
    }// </editor-fold>//GEN-END:initComponents

    public void save() {
        new FileManipulat().saveObject(datafile, database);
    }

    private Database load() {

        return (new FileManipulat().loadSetting(datafile));

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables

   
   

  
}
